apiVersion: v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchlabels:
      app: vprodb
  replica: 1
  template:
    metadata:
      labels:
        app: vproapp
  spec:
    containers:
      - name: vprodb
        image: vprofile/vprofileedb:v1
        volumeMount:
          -mountPath: /var/lib/mysql
          name: vpro-db-data
        ports:
          - name: vprodb-port
            containerPort: 3306
        env:
          - name: MYSQL_ROOT_PAASSWORD
            valuesfrom:
              secretkeyRef:
                name: app-secret
                key: db-pass
    nodeSelector:
      zone: us-east-1c
    volumes:
      - name: vpro-db-data
        awsElasticBlockStore:
          volumeID: vol-03e527e251f1bcb04
          fstype: ext4

    initContainers:
      - name: busybox
        image: busybox:latest
        args: ["rm","-rf","var/lib/mysql/lost-found"]
        volumesMount:
          - name: vpro-db-data
            mountPath: /var/lib/mysql